'use client'
import React from 'react'
import { WeeklyPlan } from '@/app/fitness-planner/page'

interface WeeklyPlanDisplayProps {
  plan: WeeklyPlan[]
  onRegeneratePlan?: () => void
}

export function WeeklyPlanDisplay({ plan, onRegeneratePlan }: WeeklyPlanDisplayProps) {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-emerald-500/20 to-emerald-600/20 border border-emerald-500/30 rounded-xl p-6 backdrop-blur-sm">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-emerald-300 flex items-center">
              <span className="mr-3">💪</span>
              Your Weekly Fitness & Meal Plan
            </h2>
            <p className="text-emerald-200/80 mt-2">Generated by J.A.R.V.I.S AI • Saved to your profile</p>
          </div>
          {onRegeneratePlan && (
            <button
              onClick={onRegeneratePlan}
              className="bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 px-4 py-2 rounded-lg transition-colors flex items-center space-x-2 border border-emerald-500/30"
            >
              <span>🔄</span>
              <span>Regenerate</span>
            </button>
          )}
        </div>
      </div>

      {/* Plan Cards Grid */}
      <div className="space-y-4">
        {plan.map((day, index) => (
          <div
            key={day.day}
            className="bg-gray-800/50 border border-gray-600/30 rounded-xl backdrop-blur-sm overflow-hidden hover:border-emerald-500/30 transition-all duration-300 animate-slide-in-up"
            style={{ animationDelay: `${index * 0.1}s` }}
          >
            {/* Day Header */}
            <div className="bg-gradient-to-r from-gray-700/50 to-gray-800/50 p-4 border-b border-gray-600/30">
              <div className="flex items-center space-x-4">
                <div className="bg-emerald-500/20 text-emerald-300 px-4 py-2 rounded-full text-sm font-bold border border-emerald-500/30">
                  Day {day.day}
                </div>
                <h3 className="text-xl font-bold text-white">{day.dayName}</h3>
              </div>
            </div>

            {/* Content Grid */}
            <div className="p-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Workout Section */}
              <div className="space-y-4">
                <div className="flex items-center space-x-2 mb-3">
                  <span className="text-blue-400 text-xl">🏋️‍♂️</span>
                  <h4 className="text-lg font-semibold text-blue-300">Workout</h4>
                </div>
                <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                  <p className="text-gray-200 leading-relaxed">{day.workout}</p>
                </div>
              </div>

              {/* Meals Section */}
              <div className="space-y-4">
                <div className="flex items-center space-x-2 mb-3">
                  <span className="text-orange-400 text-xl">🍽️</span>
                  <h4 className="text-lg font-semibold text-orange-300">Meals</h4>
                </div>
                
                <div className="space-y-3">
                  {/* Breakfast */}
                  <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">
                    <div className="flex items-center space-x-2 mb-2">
                      <span className="text-yellow-400">🌅</span>
                      <span className="text-yellow-300 font-medium text-sm">Breakfast</span>
                    </div>
                    <p className="text-gray-300 text-sm">{day.breakfast}</p>
                  </div>

                  {/* Lunch */}
                  <div className="bg-orange-500/10 border border-orange-500/20 rounded-lg p-3">
                    <div className="flex items-center space-x-2 mb-2">
                      <span className="text-orange-400">☀️</span>
                      <span className="text-orange-300 font-medium text-sm">Lunch</span>
                    </div>
                    <p className="text-gray-300 text-sm">{day.lunch}</p>
                  </div>

                  {/* Snack */}
                  <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-3">
                    <div className="flex items-center space-x-2 mb-2">
                      <span className="text-purple-400">🍎</span>
                      <span className="text-purple-300 font-medium text-sm">Snack</span>
                    </div>
                    <p className="text-gray-300 text-sm">{day.snack}</p>
                  </div>

                  {/* Dinner */}
                  <div className="bg-indigo-500/10 border border-indigo-500/20 rounded-lg p-3">
                    <div className="flex items-center space-x-2 mb-2">
                      <span className="text-indigo-400">🌙</span>
                      <span className="text-indigo-300 font-medium text-sm">Dinner</span>
                    </div>
                    <p className="text-gray-300 text-sm">{day.dinner}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Action Buttons */}
      <div className="bg-gray-800/50 border border-gray-600/30 rounded-xl p-6 backdrop-blur-sm">
        <div className="text-center mb-4">
          <h3 className="text-lg font-semibold text-gray-200">Export Your Plan</h3>
          <p className="text-gray-400 text-sm">Take your plan with you</p>
        </div>
        
        <div className="flex flex-wrap gap-4 justify-center">
          <button
            onClick={() => window.print()}
            className="bg-blue-500/20 hover:bg-blue-500/30 text-blue-300 px-6 py-3 rounded-lg transition-all duration-200 flex items-center space-x-2 border border-blue-500/30 hover:border-blue-400/50"
          >
            <span>🖨️</span>
            <span>Print Plan</span>
          </button>
          
          <button
            onClick={() => {
              const text = plan.map(day => 
                `=== ${day.dayName.toUpperCase()} (Day ${day.day}) ===\n` +
                `🏋️‍♂️ WORKOUT:\n${day.workout}\n\n` +
                `🍽️ MEALS:\n` +
                `🌅 Breakfast: ${day.breakfast}\n` +
                `☀️ Lunch: ${day.lunch}\n` +
                `🍎 Snack: ${day.snack}\n` +
                `🌙 Dinner: ${day.dinner}\n\n`
              ).join('')
              
              navigator.clipboard.writeText(text).then(() => {
                // You could add a toast notification here
                alert('Plan copied to clipboard!')
              })
            }}
            className="bg-purple-500/20 hover:bg-purple-500/30 text-purple-300 px-6 py-3 rounded-lg transition-all duration-200 flex items-center space-x-2 border border-purple-500/30 hover:border-purple-400/50"
          >
            <span>📋</span>
            <span>Copy Text</span>
          </button>
          
          <button
            onClick={() => {
              const dataStr = JSON.stringify({
                generatedAt: new Date().toISOString(),
                weeklyPlan: plan
              }, null, 2)
              const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr)
              const exportFileDefaultName = `fitness-plan-${new Date().toISOString().split('T')[0]}.json`
              const linkElement = document.createElement('a')
              linkElement.setAttribute('href', dataUri)
              linkElement.setAttribute('download', exportFileDefaultName)
              linkElement.click()
            }}
            className="bg-green-500/20 hover:bg-green-500/30 text-green-300 px-6 py-3 rounded-lg transition-all duration-200 flex items-center space-x-2 border border-green-500/30 hover:border-green-400/50"
          >
            <span>💾</span>
            <span>Download JSON</span>
          </button>
        </div>
      </div>
    </div>
  )
} 